### ISSUE TITLE
Roadmap ?

### ISSUE THREAD

**Issue by elmatou** [spk/ruby-apt-pkg#1]
Hi,
I'm currently working on ruby wrapper for the different apt tools, when I noticed your project.
It is very interressting as it avoid messy system calls by binding it to the C header.
As of now implement only few of the possibilities offered by APT. Are you planning to implement new features (install, remove, ...) ?
Any how, I really want to see this going further, I will digg to understand wat I need to know to write the other features, and If you want will PR some of my improvements (if it happens to be...).

see you

**Comment by elmatou** [comment]
Hi Laurent,
I see, you are working on it again. I definitely will need something like what you are achieving.

I was ready to begin my implemetation with https://github.com/ffi/ffi.
I do prefer the approch because I have a very little experience with C/C++

If you are willing to change your strategy and go with ffi (https://github.com/ffi/ffi/wiki/why-use-ffi) I will be very happy to help.

See you.

**Comment by spk** [comment]
Hi,
One of the goal of this project is to learn Ruby ABI, so I will not change the implementation.
If you have a repository I can add it to README or could help maybe.
Thanks for your interest.
